In [1]:
import pandas as pd

In [2]:
df18 = pd.read_csv('df18_preprocess.csv')
df19 = pd.read_csv('df19_preprocess.csv')
df20 = pd.read_csv('df20_preprocess.csv')

In [3]:
len(df18)

73538

In [4]:
len(df19)

68092

In [5]:
len(df20)

98586

In [6]:
train_set = pd.concat([df18, df19]).drop_duplicates()

In [7]:
test_set = df20.copy()

In [8]:
train_set.head()

specialty  \
0   Інженеріяпрограмногозабезпечення   
13  Інженеріяпрограмногозабезпечення   
14  Інженеріяпрограмногозабезпечення   
19  Інженеріяпрограмногозабезпечення   
24  Інженеріяпрограмногозабезпечення   

                                           university priority   mark kvota  \
0   Національний технічний університет України «Ки...        1  200.0   NaN   
13  Національний технічний університет України «Ки...        К  200.0   NaN   
14  Національний технічний університет України «Ки...        2  200.0   NaN   
19  Національний технічний університет України «Ки...        3  200.0   NaN   
24  Національний технічний університет України «Ки...        4  200.0   NaN   

    placesCount  budgetCount  contractCount  vstup  budget_mark_mean_previous  \
0           257          141            116   True                  191.97133   
13          257          141            116  False                  191.97133   
14          257          141            116  False                  191.97133   
19          257          141            116  False                  191.97133   
24          257          141            116  False                  191.97133   

    mark_mean_previous  abit_count_previous  mark_max_previous  \
0           173.384867          2072.000935              200.0   
13          173.384867          2072.000935              200.0   
14          173.384867          2072.000935              200.0   
19          173.384867          2072.000935              200.0   
24          173.384867          2072.000935              200.0   

    mark_min_previous  budget_mark_max_previous  
0          118.687881                198.551103  
13         118.687881                198.551103  
14         118.687881                198.551103  
19         118.687881                198.551103  
24         118.687881                198.551103

In [9]:
train_set.priority.unique()

array(['1', 'К', '2', '3', '4', '5', '6', '7'], dtype=object)

In [10]:
test_set.priority.unique()

array(['5', '2', '3', '1', '4', 'К'], dtype=object)

In [11]:
train_set.kvota.unique()

array([nan, 'Квота-1'], dtype=object)

In [12]:
test_set.kvota.unique()

array([nan, 'Квота-1', 'Квота-2'], dtype=object)

In [13]:
train_set.vstup.unique()

array([ True, False])

In [14]:
test_set.vstup.unique()

array([False,  True])

In [15]:
train_set.describe()

mark    placesCount    budgetCount  contractCount  \
count  131159.000000  131159.000000  131159.000000   1.311590e+05   
mean      167.188628     147.528778      67.969419   8.401022e+07   
std        18.294328     101.831142      56.800820   4.031295e+08   
min       103.785000      10.000000       2.000000   1.000000e+00   
25%       154.452000      70.000000      23.000000   5.000000e+00   
50%       169.600000     120.000000      57.000000   4.100000e+01   
75%       181.764000     200.000000      95.000000   9.900000e+01   
max       200.000000     500.000000     229.000000   2.018501e+09   

       budget_mark_mean_previous  mark_mean_previous  abit_count_previous  \
count              131159.000000       131159.000000        131159.000000   
mean                  182.740868          166.187250           999.562284   
std                    10.031438            6.277082           737.235383   
min                   134.954200          141.160771            19.000000   
25%                   180.144517          162.033586           392.717293   
50%                   185.423790          167.850803           803.997277   
75%                   189.981333          171.152723          1446.000000   
max                   198.270500          182.243705          2672.000000   

       mark_max_previous  mark_min_previous  budget_mark_max_previous  
count      131159.000000      131159.000000             131159.000000  
mean          198.868049         116.498194                195.318013  
std             2.638528           5.356962                  5.184409  
min           175.083000         100.647000                158.202000  
25%           199.688202         113.424000                193.289000  
50%           200.000000         116.127317                197.315618  
75%           200.000000         118.900000                198.800720  
max           200.000000         144.024000                200.000000

In [16]:
test_set.describe()

mark   placesCount   budgetCount  contractCount  \
count  98586.000000  98586.000000  98586.000000   98586.000000   
mean     167.481029    150.991642     73.056144      58.141105   
std       18.666775    107.183353     67.413742      71.654635   
min      103.740000      8.000000      3.000000       2.000000   
25%      154.326000     70.000000     22.000000       2.000000   
50%      169.500000    120.000000     59.000000      30.000000   
75%      182.500000    200.000000    107.000000      95.000000   
max      200.000000    450.000000    296.000000     328.000000   

       budget_mark_mean_previous  mark_mean_previous  abit_count_previous  \
count               98586.000000        98586.000000         98586.000000   
mean                  183.395106          167.596558           861.810660   
std                    10.107032            7.049031           614.298936   
min                   143.138235          139.322809            22.000000   
25%                   182.149615          163.125365           366.540356   
50%                   185.467631          168.508683           651.884314   
75%                   190.041667          172.062701          1342.355836   
max                   199.278200          182.897357          2241.000000   

       mark_max_previous  mark_min_previous  budget_mark_max_previous  
count       98586.000000       98586.000000              98586.000000  
mean          198.807652         118.373742                195.677287  
std             2.641735          10.434078                  5.270061  
min           179.300000         101.847000                164.570000  
25%           198.900000         110.400000                193.569808  
50%           200.000000         116.000000                197.472797  
75%           200.000000         125.800000                200.000000  
max           200.000000         142.444781                200.000000

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
priority_encoder = OneHotEncoder()
priority_encoder.fit(train_set.priority.to_numpy().reshape(-1, 1))
priority_cols_names = priority_encoder.get_feature_names_out()
for col_i in range(len(priority_cols_names)):
    priority_cols_names[col_i] = priority_cols_names[col_i].replace('x0_', 'priority_')
train_set[priority_cols_names] = pd.DataFrame(priority_encoder.transform(train_set.priority.to_numpy().reshape(-1, 1)).toarray(), columns = priority_cols_names)
test_set[priority_cols_names] = pd.DataFrame(priority_encoder.transform(test_set.priority.to_numpy().reshape(-1, 1)).toarray(), columns = priority_cols_names)

In [19]:
train_set = train_set.drop('priority', axis = 1)
test_set = test_set.drop('priority', axis = 1)

In [20]:
import numpy as np

In [21]:
test_set['kvota'] = test_set.kvota.apply(lambda x : np.nan if x == 'Квота-2' else x)

In [22]:
kvota_encoder = OneHotEncoder()
kvota_encoder.fit(train_set.kvota.to_numpy().reshape(-1, 1))
kvota_cols_names = kvota_encoder.get_feature_names_out()
for col_i in range(len(kvota_cols_names)):
    kvota_cols_names[col_i] = kvota_cols_names[col_i].replace('x0_', 'kvota_')
train_set[kvota_cols_names] = pd.DataFrame(kvota_encoder.transform(train_set.kvota.to_numpy().reshape(-1, 1)).toarray(), columns = kvota_cols_names)
test_set[kvota_cols_names] = pd.DataFrame(kvota_encoder.transform(test_set.kvota.to_numpy().reshape(-1, 1)).toarray(), columns = kvota_cols_names)

In [23]:
train_set = train_set.drop('kvota_nan', axis = 1)
test_set = test_set.drop('kvota_nan', axis = 1)

In [24]:
train_set.columns

Index(['specialty', 'university', 'mark', 'kvota', 'placesCount',
       'budgetCount', 'contractCount', 'vstup', 'budget_mark_mean_previous',
       'mark_mean_previous', 'abit_count_previous', 'mark_max_previous',
       'mark_min_previous', 'budget_mark_max_previous', 'priority_1',
       'priority_2', 'priority_3', 'priority_4', 'priority_5', 'priority_6',
       'priority_7', 'priority_К', 'kvota_Квота-1'],
      dtype='object')

In [25]:
train_set['mark_2_budget_mark_max'] = train_set.mark / train_set.budget_mark_mean_previous
train_set['mark_2_mark_mean_previous'] = train_set.mark / train_set.mark_mean_previous
train_set['mark_2_mark_max_previous'] = train_set.mark / train_set.mark_max_previous
train_set['mark_2_mark_min_previous'] = train_set.mark / train_set.mark_min_previous
train_set['mark_2_budget_mark_max_previous'] = train_set.mark / train_set.budget_mark_max_previous

In [26]:
test_set['mark_2_budget_mark_max'] = test_set.mark / test_set.budget_mark_mean_previous
test_set['mark_2_mark_mean_previous'] = test_set.mark / test_set.mark_mean_previous
test_set['mark_2_mark_max_previous'] = test_set.mark / test_set.mark_max_previous
test_set['mark_2_mark_min_previous'] = test_set.mark / test_set.mark_min_previous
test_set['mark_2_budget_mark_max_previous'] = test_set.mark / test_set.budget_mark_max_previous

In [27]:
train_set.columns

Index(['specialty', 'university', 'mark', 'kvota', 'placesCount',
       'budgetCount', 'contractCount', 'vstup', 'budget_mark_mean_previous',
       'mark_mean_previous', 'abit_count_previous', 'mark_max_previous',
       'mark_min_previous', 'budget_mark_max_previous', 'priority_1',
       'priority_2', 'priority_3', 'priority_4', 'priority_5', 'priority_6',
       'priority_7', 'priority_К', 'kvota_Квота-1', 'mark_2_budget_mark_max',
       'mark_2_mark_mean_previous', 'mark_2_mark_max_previous',
       'mark_2_mark_min_previous', 'mark_2_budget_mark_max_previous'],
      dtype='object')

In [28]:
scaling_columns = ['mark', 'placesCount',
       'budgetCount', 'contractCount', 'budget_mark_mean_previous',
       'mark_mean_previous', 'abit_count_previous', 'mark_max_previous',
       'mark_min_previous', 'budget_mark_max_previous', 'mark_2_budget_mark_max',
       'mark_2_mark_mean_previous', 'mark_2_mark_max_previous',
       'mark_2_mark_min_previous', 'mark_2_budget_mark_max_previous']

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler = MinMaxScaler()
scaler.fit(train_set[scaling_columns])
train_set[scaling_columns] = pd.DataFrame(scaler.transform(train_set[scaling_columns]), columns = scaler.get_feature_names_out())
test_set[scaling_columns] = pd.DataFrame(scaler.transform(test_set[scaling_columns]), columns = scaler.get_feature_names_out())

In [31]:
train_set.head()

specialty  \
0   Інженеріяпрограмногозабезпечення   
13  Інженеріяпрограмногозабезпечення   
14  Інженеріяпрограмногозабезпечення   
19  Інженеріяпрограмногозабезпечення   
24  Інженеріяпрограмногозабезпечення   

                                           university      mark kvota  \
0   Національний технічний університет України «Ки...  1.000000   NaN   
13  Національний технічний університет України «Ки...  0.979733   NaN   
14  Національний технічний університет України «Ки...  0.979213   NaN   
19  Національний технічний університет України «Ки...  0.975576   NaN   
24  Національний технічний університет України «Ки...  0.973497   NaN   

    placesCount  budgetCount  contractCount  vstup  budget_mark_mean_previous  \
0      0.504082     0.612335   5.697296e-08   True                   0.900513   
13     0.504082     0.612335   5.697296e-08  False                   0.900513   
14     0.504082     0.612335   5.697296e-08  False                   0.900513   
19     0.504082     0.612335   5.697296e-08  False                   0.900513   
24     0.504082     0.612335   5.697296e-08  False                   0.900513   

    mark_mean_previous  ...  priority_5  priority_6  priority_7  priority_К  \
0             0.784367  ...         0.0         0.0         0.0         0.0   
13            0.784367  ...         0.0         0.0         0.0         0.0   
14            0.784367  ...         0.0         0.0         0.0         0.0   
19            0.784367  ...         0.0         0.0         0.0         0.0   
24            0.784367  ...         0.0         0.0         0.0         0.0   

    kvota_Квота-1  mark_2_budget_mark_max  mark_2_mark_mean_previous  \
0             0.0                0.594502                   0.679591   
13            0.0                0.582151                   0.665495   
14            0.0                0.581835                   0.665134   
19            0.0                0.579618                   0.662604   
24            0.0                0.578351                   0.661158   

    mark_2_mark_max_previous  mark_2_mark_min_previous  \
0                   0.771707                  0.729964   
13                  0.756067                  0.715275   
14                  0.755666                  0.714899   
19                  0.752859                  0.712262   
24                  0.751255                  0.710756   

    mark_2_budget_mark_max_previous  
0                          0.698660  
13                         0.684529  
14                         0.684167  
19                         0.681631  
24                         0.680182  

[5 rows x 28 columns]

In [32]:
train_set.vstup.value_counts()

vstup
False    119830
True      11329
Name: count, dtype: int64

In [33]:
119830 / 11329

10.577279548062494

In [34]:
test_set.vstup.value_counts()

vstup
False    88867
True      9719
Name: count, dtype: int64

In [35]:
88867 / 9719

9.143636176561374

In [37]:
from imblearn.over_sampling import RandomOverSampler

In [38]:
ros = RandomOverSampler(random_state=0)

In [39]:
X_resampled, y_resampled = ros.fit_resample(train_set.drop('vstup', axis = 1), train_set.vstup)

In [40]:
X_resampled

specialty  \
0       Інженеріяпрограмногозабезпечення   
1       Інженеріяпрограмногозабезпечення   
2       Інженеріяпрограмногозабезпечення   
3       Інженеріяпрограмногозабезпечення   
4       Інженеріяпрограмногозабезпечення   
...                                  ...   
239655                             Право   
239656  Інженеріяпрограмногозабезпечення   
239657                 Прикладнамеханіка   
239658                          Біологія   
239659                       Електроніка   

                                               university      mark kvota  \
0       Національний технічний університет України «Ки...  1.000000   NaN   
1       Національний технічний університет України «Ки...  0.979733   NaN   
2       Національний технічний університет України «Ки...  0.979213   NaN   
3       Національний технічний університет України «Ки...  0.975576   NaN   
4       Національний технічний університет України «Ки...  0.973497   NaN   
...                                                   ...       ...   ...   
239655  Львівський національний університет імені Іван...  0.873014   NaN   
239656  Національний технічний університет України «Ки...  0.426805   NaN   
239657  Національний технічний університет України «Ки...  0.706990   NaN   
239658  Львівський національний університет імені Іван...  0.832729   NaN   
239659  Національний технічний університет України «Ки...  0.914358   NaN   

        placesCount  budgetCount  contractCount  budget_mark_mean_previous  \
0          0.504082     0.612335   5.697296e-08                   0.900513   
1          0.504082     0.612335   5.697296e-08                   0.900513   
2          0.504082     0.612335   5.697296e-08                   0.900513   
3          0.504082     0.612335   5.697296e-08                   0.900513   
4          0.504082     0.612335   5.697296e-08                   0.900513   
...             ...          ...            ...                        ...   
239655     0.387755     0.105727   8.570715e-08                   0.760029   
239656     0.142857     0.246696   1.040376e-08                   0.900513   
239657     0.040816     0.048458   9.999694e-01                   0.660153   
239658     0.173469     0.409692   9.999710e-01                   0.749100   
239659     0.132653     0.321586   9.999705e-01                   0.782293   

        mark_mean_previous  abit_count_previous  ...  priority_5  priority_6  \
0                 0.784367             0.773841  ...         0.0         0.0   
1                 0.784367             0.773841  ...         0.0         0.0   
2                 0.784367             0.773841  ...         0.0         0.0   
3                 0.784367             0.773841  ...         0.0         0.0   
4                 0.784367             0.773841  ...         0.0         0.0   
...                    ...                  ...  ...         ...         ...   
239655            0.519225             0.419148  ...         0.0         1.0   
239656            0.784367             0.773841  ...         0.0         0.0   
239657            0.248464             0.120995  ...         0.0         1.0   
239658            0.535552             0.369393  ...         0.0         0.0   
239659            0.671605             0.461383  ...         0.0         0.0   

        priority_7  priority_К  kvota_Квота-1  mark_2_budget_mark_max  \
0              0.0         0.0            0.0                0.594502   
1              0.0         0.0            0.0                0.582151   
2              0.0         0.0            0.0                0.581835   
3              0.0         0.0            0.0                0.579618   
4              0.0         0.0            0.0                0.578351   
...            ...         ...            ...                     ...   
239655         0.0         0.0            0.0                0.574903   
239656         0.0         1.0            0.0                0.245214   
239657         0.0    

In [41]:
y_resampled

0          True
1         False
2         False
3         False
4         False
          ...  
239655     True
239656     True
239657     True
239658     True
239659     True
Name: vstup, Length: 239660, dtype: bool

In [42]:
train_set = X_resampled.copy()

In [43]:
train_set['vstup'] = y_resampled

In [44]:
train_set.vstup.unique()

array([ True, False])

In [46]:
train_set['vstup'] = train_set.vstup.apply(lambda x : 1 if x else 0)

In [47]:
test_set.vstup.unique()

array([False,  True])

In [48]:
test_set['vstup'] = test_set.vstup.apply(lambda x : 1 if x else 0)

In [49]:
train_set.vstup.value_counts()

vstup
1    119830
0    119830
Name: count, dtype: int64

In [50]:
test_set.vstup.value_counts()

vstup
0    88867
1     9719
Name: count, dtype: int64

In [51]:
train_set.to_csv('train_set.csv', index = False)
test_set.to_csv('test_set.csv', index = False)